nome_completo = input("Digite o nome completo do aluno: ")
matricula_str = input("Digite a matrícula do aluno: ")
nota1_str = input("Digite a primeira nota: ")
nota2_str = input("Digite a segunda nota: ")
matricula = int(matricula_str)
nota1 = float(nota1_str)
nota2 = float(nota2_str)
media = (nota1 + nota2) / 2
print("\n" + "="*30)
print(f"{'HISTÓRICO ESCOLAR':^30}")
print("="*30)
print(f"Nome: {nome_completo}")
print(f"Matrícula: {matricula}")
print(f"Nota 1: {nota1:.2f}")
print(f"Nota 2: {nota2:.2f}")
print(f"Média Final: {media:.2f}")
print("="*30)